import { prisma } from '@/lib/db';
import { normalizeMalaysiaPhone } from '@/lib/staff';
import { PartTimerLookup } from '../PartTimerLookup';
import { uploadPortfolioMedia } from '../actions';

export default async function PartTimerPortfolioPage({ searchParams }: { searchParams: { phone?: string; error?: string; uploaded?: string } }) {
  const phone = normalizeMalaysiaPhone(searchParams.phone || '');
  const partTimer = phone ? await prisma.staff.findUnique({ where: { phoneE164: phone }, include: { portfolioMedia: { orderBy: { createdAt: 'desc' } } } }) : null;
  return <PartTimerLookup phone={phone || searchParams.phone}>{!partTimer ? <div className="card card-pad text-sm text-ink-500">Enter your WhatsApp number to manage portfolio.</div> : <div className="space-y-5"><div className="card card-pad"><h1 className="sectiontitle">Portfolio</h1><p className="subtitle">Upload work samples for employers to review.</p>{searchParams.uploaded && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Media uploaded.</p>}{searchParams.error && <p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{searchParams.error}</p>}<form action={uploadPortfolioMedia} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="phone" value={phone} /><div><label className="label">Title</label><input className="input" name="title" placeholder="Roadshow setup" /></div><div><label className="label">Media file</label><input className="input" name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" required /></div><div className="md:col-span-2"><label className="label">Description</label><textarea className="input min-h-[90px]" name="description" placeholder="What did you do in this work sample?" /></div><div className="md:col-span-2"><button className="btn-primary" type="submit">Upload media</button></div></form></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{partTimer.portfolioMedia.length === 0 && <div className="card card-pad text-sm text-ink-500">No portfolio media yet.</div>}{partTimer.portfolioMedia.map((media) => <div key={media.id} className="card overflow-hidden"><div className="aspect-video bg-ink-100">{media.mediaType === 'VIDEO' ? <video src={media.url} controls className="h-full w-full object-cover" /> : <img src={media.url} alt={media.title || 'Portfolio media'} className="h-full w-full object-cover" />}</div><div className="p-4"><div className="font-medium text-ink-950">{media.title || media.filename || 'Portfolio media'}</div><div className="mt-1 text-sm text-ink-500">{media.description || media.mimeType}</div></div></div>)}</div></div>}</PartTimerLookup>;
}