import { prisma } from '@/lib/db';
import { currentAdminTenantId } from '@/lib/tenant';
import { OFFER_STATUS_LABELS } from '@/lib/marketplace';
import { defaultOfferMessage } from '@/lib/offer-messages';
import { sendJobOffer } from './actions';

export default async function EmployerOffersPage({ searchParams }: { searchParams: { jobId?: string; partTimerId?: string | string[]; sent?: string; total?: string; error?: string } }) {
  const tenantId = await currentAdminTenantId();
  const offers = await prisma.jobOffer.findMany({ where: tenantId ? { tenantId } : {}, include: { job: true, recipients: { include: { partTimer: true } } }, orderBy: { createdAt: 'desc' }, take: 100 });
  const selectedIds = Array.isArray(searchParams.partTimerId) ? searchParams.partTimerId : searchParams.partTimerId ? [searchParams.partTimerId] : [];
  const selectedJob = searchParams.jobId ? await prisma.workEvent.findUnique({ where: { id: searchParams.jobId } }) : null;
  const selectedPartTimers = selectedIds.length > 0 ? await prisma.staff.findMany({ where: { id: { in: selectedIds }, active: true, status: 'ACTIVE' }, orderBy: { fullName: 'asc' } }) : [];
  return <div className="space-y-5"><div><h1 className="sectiontitle">Offers</h1><p className="subtitle">WhatsApp offer batches and recipient status.</p></div>{searchParams.sent && <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Sent {searchParams.sent} of {searchParams.total || searchParams.sent} offers.</div>}{searchParams.error && <div className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{searchParams.error}</div>}{selectedJob && <form action={sendJobOffer} className="card card-pad space-y-4"><div><div className="font-semibold">Prepared offer for {selectedJob.name}</div><p className="mt-1 text-sm text-ink-500">Selected recipients: {selectedPartTimers.length}</p></div><input type="hidden" name="jobId" value={selectedJob.id} />{selectedPartTimers.map((partTimer) => <input key={partTimer.id} type="hidden" name="partTimerId" value={partTimer.id} />)}<div><label className="label">Title</label><input className="input" name="title" defaultValue={`Offer: ${selectedJob.name}`} /></div><div><label className="label">Message</label><textarea className="input min-h-[220px]" name="message" defaultValue={defaultOfferMessage(selectedJob)} /></div><div className="rounded-lg bg-ink-50 p-3 text-sm text-ink-600">Use {'{name}'} to personalize each message. Replies are interpreted as 1 = interested, 2 = not interested.</div><button className="btn-primary" type="submit" disabled={selectedPartTimers.length === 0}>Send WhatsApp offer</button></form>}<div className="card overflow-hidden"><table className="table-base"><thead><tr><th>Offer</th><th>Job</th><th>Recipients</th><th>Status</th></tr></thead><tbody>{offers.length === 0 && <tr><td colSpan={4} className="py-10 text-center text-ink-500">No offers yet.</td></tr>}{offers.map((offer) => <tr key={offer.id}><td>{offer.title}</td><td>{offer.job.name}</td><td>{offer.recipients.length}</td><td>{offer.status}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:grid-cols-2">{offers.flatMap((offer) => offer.recipients.map((recipient) => <div key={recipient.id} className="card card-pad"><div className="font-medium text-ink-950">{recipient.partTimer.fullName}</div><div className="text-sm text-ink-500">{offer.job.name}</div><div className="mt-2 text-sm font-semibold">{OFFER_STATUS_LABELS[recipient.status] || recipient.status}</div></div>))}</div></div>;
}